branches:
  only:
    - master

matrix:
  include:
    - script:
        - set -o pipefail
        - xcodebuild $XCODE_ACTION -scheme BoostBLEKit | xcpretty
        - xcodebuild $XCODE_ACTION -scheme BoostBLEKit -sdk iphonesimulator -destination "name=iPhone SE" | xcpretty
        - xcodebuild $XCODE_ACTION -scheme BoostBLEKit -sdk appletvsimulator -destination "name=Apple TV 1080p" | xcpretty
        - xcodebuild build -scheme BoostBLEKit -sdk watchsimulator | xcpretty
      env:
        - JOB=Xcode
        - XCODE_ACTION="build-for-testing test-without-building"
      os: osx
      osx_image: xcode10.3
      language: swift
    - script:
        - swift --version
        - swift build
        - swift test
      env: JOB=SPM
      os: osx
      osx_image: xcode10.3
      language: swift

notifications:
  email: false