branches:
  only:
    - master

matrix:
  include:
    - script:
        - set -o pipefail
        - xcodebuild $XCODE_ACTION -scheme BoostBLEKit | xcpretty
        - xcodebuild $XCODE_ACTION -scheme BoostBLEKit -sdk iphonesimulator | xcpretty
        - xcodebuild $XCODE_ACTION -scheme BoostBLEKit -sdk appletvsimulator | xcpretty
        - xcodebuild build -scheme BoostBLEKit -sdk watchsimulator | xcpretty
      env:
        - JOB=Xcode
        - XCODE_ACTION="build-for-testing test-without-building"
      os: osx
      osx_image: xcode10.3
      language: objective-c
    - script:
        - swift --version
        - swift build
        - swift test
      os: osx
      osx_image: xcode10.3
      language: generic

notifications:
  email: false